name: Deploy to DreamHost

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to DreamHost via SSH
        env:
          SSH_KEY: ${{ secrets.DH_KEY }}
        run: |
          echo "$SSH_KEY" > key
          chmod 600 key
          git config --global user.name "GitHub Action"
          git config --global user.email "gh-action@charleswilke.com"
          git remote add production "ssh://dh_528u8k@iad1-shared-b8-12.dreamhost.com/~/git/charleswilke.com.git"
          GIT_SSH_COMMAND="ssh -i key -o StrictHostKeyChecking=no" git push --force production main

